application: quoteurl
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /skin
  static_dir: skin

- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(favicon\.ico|robots\.txt)

- url: /.*
  script: main.py